export const crosswordData = {
  id: 'custom/1',
  number: 1,
  name: 'Custom Crossword',
  date: new Date().getTime(),
  entries: [
    {
      id: '1-across',
      number: 1,
      humanNumber: '1',
      clue: 'Autumn symbol with a particular sentimental value (4)',
      direction: 'across',
      length: 4,
      group: ['1-across'],
      position: { x: 7, y: 1 },
      separatorLocations: {},
      solution: 'LEAF'
    },
    {
      id: '3-across',
      number: 3,
      humanNumber: '3',
      clue: 'Iconic powder used in your homemade drinks (6)',
      direction: 'across',
      length: 6,
      group: ['3-across'],
      position: { x: 9, y: 3 },
      separatorLocations: {},
      solution: 'MATCHA'
    },
    {
      id: '5-across',
      number: 5,
      humanNumber: '5',
      clue: 'Artist that made me buy crazy expensive water (9)',
      direction: 'across',
      length: 9,
      group: ['5-across'],
      position: { x: 6, y: 5 },
      separatorLocations: {},
      solution: 'ONEOKROCK'
    },
    {
      id: '7-across',
      number: 7,
      humanNumber: '7',
      clue: 'The greatest duck of all time (6)',
      direction: 'across',
      length: 6,
      group: ['7-across'],
      position: { x: 3, y: 7 },
      separatorLocations: {},
      solution: 'BENSON'
    },
    {
      id: '9-across',
      number: 9,
      humanNumber: '9',
      clue: 'Made you wait a bit too long in my room for this dish (8)',
      direction: 'across',
      length: 8,
      group: ['9-across'],
      position: { x: 3, y: 9 },
      separatorLocations: {},
      solution: 'TSUKEMEN'
    },
    {
      id: '12-across',
      number: 12,
      humanNumber: '12',
      clue: 'Festive plant sponsored by DIOR (13)',
      direction: 'across',
      length: 13,
      group: ['12-across'],
      position: { x: 7, y: 13 },
      separatorLocations: {},
      solution: 'CHRISTMASTREE'
    },
    {
      id: '14-across',
      number: 14,
      humanNumber: '14',
      clue: 'Signature Hazukido item (9)',
      direction: 'across',
      length: 9,
      group: ['14-across'],
      position: { x: 3, y: 15 },
      separatorLocations: {},
      solution: 'CROISSANT'
    },
    {
      id: '15-across',
      number: 15,
      humanNumber: '15',
      clue: 'Adjective to describe a pair of sensory organs (6)',
      direction: 'across',
      length: 6,
      group: ['15-across'],
      position: { x: 13, y: 15 },
      separatorLocations: {},
      solution: 'GOOGLY'
    },
    {
      id: '16-across',
      number: 16,
      humanNumber: '16',
      clue: 'Scary building to be in for the first time past 10 pm (10)',
      direction: 'across',
      length: 10,
      group: ['16-across'],
      position: { x: 4, y: 17 },
      separatorLocations: {},
      solution: 'DANAPORTER'
    },
    {
      id: '17-across',
      number: 17,
      humanNumber: '17',
      clue: 'I am Yoo ____! (9)',
      direction: 'across',
      length: 9,
      group: ['17-across'],
      position: { x: 3, y: 21 },
      separatorLocations: {},
      solution: 'JOONGHYUK'
    },
    {
      id: '1-down',
      number: 1,
      humanNumber: '1',
      clue: 'Citrus ingredient used in a potluck item (5)',
      direction: 'down',
      length: 5,
      group: ['1-down'],
      position: { x: 7, y: 1 },
      separatorLocations: {},
      solution: 'LEMON'
    },
    {
      id: '2-down',
      number: 2,
      humanNumber: '2',
      clue: 'e.g. Lily of the valley (7)',
      direction: 'down',
      length: 7,
      group: ['2-down'],
      position: { x: 4, y: 3 },
      separatorLocations: {},
      solution: 'FLOWERS'
    },
    {
      id: '4-down',
      number: 4,
      humanNumber: '4',
      clue: 'E7 staple (6)',
      direction: 'down',
      length: 6,
      group: ['4-down'],
      position: { x: 12, y: 3 },
      separatorLocations: {},
      solution: 'COOKIE'
    },
    {
      id: '6-down',
      number: 6,
      humanNumber: '6',
      clue: 'Bubble tea chain that messed up your matcha order in the past (9)',
      direction: 'down',
      length: 9,
      group: ['6-down'],
      position: { x: 14, y: 5 },
      separatorLocations: {},
      solution: 'KUNGFUTEA'
    },
    {
      id: '8-down',
      number: 8,
      humanNumber: '8',
      clue: 'There was a lot of ____ residue on one of our first walks (9)',
      direction: 'down',
      length: 9,
      group: ['8-down'],
      position: { x: 10, y: 7 },
      separatorLocations: {},
      solution: 'DANDELION'
    },
    {
      id: '10-down',
      number: 10,
      humanNumber: '10',
      clue: 'Dessert ingredient that can get pretty messy when heated (9)',
      direction: 'down',
      length: 9,
      group: ['10-down'],
      position: { x: 5, y: 11 },
      separatorLocations: {},
      solution: 'CHOCOLATE'
    },
    {
      id: '11-down',
      number: 11,
      humanNumber: '11',
      clue: 'Activity done prior to finding flavoured syrups at Sobeys (10)',
      direction: 'down',
      length: 10,
      group: ['11-down'],
      position: { x: 7, y: 12 },
      separatorLocations: {},
      solution: 'ICESKATING'
    },
    {
      id: '13-down',
      number: 13,
      humanNumber: '13',
      clue: 'Pillow (9)',
      direction: 'down',
      length: 9,
      group: ['13-down'],
      position: { x: 17, y: 13 },
      separatorLocations: {},
      solution: 'RILAKKUMA'
    }
  ],
  solutionAvailable: true,
  dateSolutionAvailable: new Date().getTime(),
  dimensions: {
    cols: 24,
    rows: 24
  },
  crosswordType: 'quick'
} as const;
